server:
  port: 8002
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护