# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #连接超时时间
  connection-timeout: 5000ms
  servlet:
    #映射项目路径
    context-path: /blog


spring:
  profiles:
    # 环境 开发dev，测试test，生产prod
    active: dev
  jackson:
    serialization:
      # jackson返回时间戳
      write-dates-as-timestamps : true
  servlet:
    multipart:
      #文件上传大小配置
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    #restFul风格：当找不到页面时，正常抛出错误，不跳转页面
    throw-exception-if-no-handler-found: true
    #仅映射static资源文件
    static-path-pattern: /static/**
  resources:
    #restFul风格: 不要为资源文件建立映射
    add-mappings: false
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
  application:
    name: manage
#mybatis
mybatis-plus:
  #mapper文件
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.gaoh.entity.manage
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty

  #mybatis原生配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #不开启二级缓存
    cache-enabled: false

blog:
  path:
    #文件上传根目录 设置
    upload: D://upFiles
    #webapp文件路径
    webapp: D://webapp
  #短信秘钥
  sms:
    accessKeyId: LTAIcuaV1o8Vp2fZ
    accessKeySecret: hpYKjWmqqNvUZDvVrmZQ9D2alWPpOd
  #阿里云oss存储配置
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: LTAI4GKNwbN6615t6ntCDF3V
    secretKey: 8pbAdBEWMvT2fSIPd8bGkRuvdl6Atc
    bucketName: gaohoos
    staticDomain: ??
